version: '4.1'

services:
  frontend:
    build: ./app
    ports:
      - ${FRONTEND_PORT_1}:${FRONTEND_PORT_2}
    restart: always

  backend:
    build: ./hotels
    ports:
      - ${BACKEND_PORT_1}:${BACKEND_PORT_2}
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  mongo_diploma_3:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - ${MONGO_PORT_1}:${MONGO_PORT_2}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - mongo_diploma_3:/data/db

volumes:
  mongo_diploma_3:
    driver: local
